version: "2"
services:
  mysql_db:
      image: "mysql:5.6"
      container_name: db
      ports:
        - "3306:3306"
      volumes:
        - ./data/:/var/lib/mysql
      environment:
        MYSQL_DATABASE: 'bd_bdguy'
        MYSQL_USER: 'appli'
        MYSQL_PASSWORD: 'appliBDpassword'
        MYSQL_ROOT_PASSWORD: 'root'
  express_api:
      image: "node:10.16.1"
      container_name: api
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./src/api:/home/node/app
      ports:
       - "3000:3000"
      command: "npm start"
      depends_on:
        - mysql_db
  angular_app:
    image: "node:10.16.1"
    container_name: app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"
    command: npm start
    depends_on:
      - express_api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
